export const duckFacts = [
  {title: "Mandarin Duck", description: "The duck swimming in the pool."},
  {title: "Mandarin Duck", description: "The duck relaxing in the pool."},
  {title: "White Duck", description: "The duck on the grass."},
  {title: "Hat Duck", description: "The duck wearing a hat on top of it's head."},
  {title: "Yellow Duck", description: "The duck is taking the photo shoot."},
  {title: "Donald Duck", description: "The duck cosplaying the Donald Duck."},
  {title: "Baby Duck", description: "The duck looked so comfortable."},
  {title: "Canadian Duck", description: "The duck becomes the ruler of the sky."},
  {title: "Rubber Duck", description: "The duck taking picture with the Rubber Duck."},
  {title: "Loving Duck", description: "The ducks love each others."},
  {title: "Canadian Duck", description: "The duck wondering in the pool."},
  {title: "Cute Duck", description: "The duck looked silly, but cute."},
  {title: "Adorable Duck", description: "The baby duck looking at you."},
  {title: "The Ducks", description: "The three muskteeer ducks."},
  {title: "Hat Duck", description: "The duck wearing a hat on top of it's head."},
  {title: "Constructor Duck", description: "The duck building the home."},
  {title: "Canadian Duck", description: "The duck taking a selfie."},
  {title: "Chubby Duck", description: "The duck is having fun with the water."},
]